auth:
  strategy: anonymous   # dev only

deployment:
  accessible_namespaces:
    - "**"
  pod_annotations:
    sidecar.istio.io/inject: "true"

external_services:
  prometheus:
    url: http://prometheus-service.dev.svc:9090

  istio:
    root_namespace: istio-system

  tracing:
    enabled: false

server:
  web_scheme: http
